- name: Install the package
  apt:
    name: "{{ package }}"
    state: latest
  notify: Copying a list
  changed_when: true

- name: Copy index.html from controller to host using template
  template:
    src: index.html.j2
    dest: "/var/www/html/index.html"
  changed_when: true
  notify: Restart the service

- name: test
  debug: 
    var: my_variable
